[package]
name = "system-deps-meta"
version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
keywords.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
cargo_metadata = "0.20"
serde = "1.0"
toml = "0.9"
cfg-expr = { version = ">= 0.17, < 0.21", features = ["targets"] }
sha256 = { version = "1.6", optional = true }
attohttpc = { version = "0.29", optional = true }
flate2 = { version = "1.1", optional = true }
xz = { version = "0.1", optional = true }
tar = { version = "0.4", optional = true }
zip = { version = "2.4", optional = true }
pkg-extractor = { path = "../../pkg_extractor/pkg_extractor", optional = true }
walkdir = "2.3"

[features]
binary = ["dep:sha256", "dep:attohttpc"]
gz = ["dep:flate2", "dep:tar"]
xz = ["dep:xz", "dep:tar"]
zip = ["dep:zip"]
pkg = ["dep:pkg-extractor"]
test = []
